---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Chrome.app
    - /Applications/Spotify.app
    - /Applications/Atom.app
    - /Applications/iTerm.app
    - /Applications/Dash.app
    folders:
    - path: ~/
    - path: ~/Applications
    - path: ~/Downloads
      sort: datemodified
  - role: cask_package
    package_name: asepsis
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: Sergio Espeja
    git_user_email: sergio.espeja@gmail.com
  ## languages
  - role: brew_package
    package_name: wget
  # - role: brew_package
  #   package_name: ansible # Hey ! Already there !

  # gui
  ## text editors
  - role: cask_package
    package_name: atom
  - role: cask_package
    package_name: vagrant
  - role: cask_package
    package_name: iterm2
  - role: cask_package
    package_name: dash
